server:
  port: 8082
#eureka8081 cloudgateway8082 auth8083 teacher8084 course8085 main8086 config8087

spring:
  cloud:
    gateway:
      routes:
      - id: Eureka
        uri: http://localhost:8081/
        predicates:
        - Path=/eureka/**

      - id: Authentication
        uri: http://localhost:8083/
        predicates:
        - Path=/auth/**

      - id: Course-Service
        uri: http://localhost:8085/
        predicates:
        - Path=/mod/**
        

      - id: Store
        uri: http://localhost:8088/
        predicates:
        - Path=/store/**

      - id: Main
        uri: http://localhost:8086/
        predicates:
        - Path=/main/**

      - id: Teacher
        uri: http://localhost:8084/
        predicates:
        - Path=/teacher/**